### ISSUE TITLE
mkdir() and unlink() function not work properly in Session.php

### ISSUE THREAD

**Issue by unrealmaow** [a-kbv/php-skype#8]
**Describe the bug**
mkdir() and unlink() functions are not working properly in Session.php file. InComplete Paramters are being passed into functions

**To Reproduce**
1. When you do first login of the account, it need to create a new directory to store skype account session but it will face insufficient permission to create director through mkdir() or to delete a directory with unlink()

**Expected behavior**
It should create directory or delete the session directory without any issue.

**Suggested Solution**
mkdir($this->sessionDir,0777, true) , pass additional parameters 0777 and true in mkdir and unlink() functions to resolve the issue. Or if you have more efficient solution, implement it and let me know too :-)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I hope this project will have active development and it may help many users. I am open for any contribution.

**Comment by a-kbv** [comment]
Dear @unrealmaow

Thank you once again for your invaluable input regarding the mkdir() and unlink() issues in Session.php. I am pleased to inform you that I have taken your concerns into consideration and the problems you've raised have been resolved as of release v3.1.4.

Regarding your recommendation to use `0777` permissions with `mkdir()`: indeed there appeared to be a permission problem. However, it's important to note that setting directory permissions to `0777` grants unlimited access to everyone, which can pose significant security risks. To ensure a good balance between operability and security, I’ve decided to go for the more limited `0755` permission setting. This should alleviate the permission issues in most standard environments while maintaining defensive security measures.

Your issue also presents the perfect opportunity to inform you that I'm considering implementing a flexible driver-based session management system that allows for the use of different storage backends. This means that users like you would have the flexibility to choose between file storage, databases, or cloud-based solutions such as AWS for managing sessions.

Your constructive feedback is the lifeblood of this project's ongoing development. Ensuring the security and functionality of the library remains primary, and user-centered contributions such as yours remain priceless in this context.

Your report has been instrumental in steering our development in a more robust and user-centric direction. I encourage you to stay connected for updates and if you're interested in contributing to this vision, your involvement would be most welcome.

Again, thank you for your report and for being a vital part of our community.

**Comment by unrealmaow** [comment]
Hello,

Thank you for your valuable response. I am currently using this library in one of my projects, and hopefully, I will start contributing to this project to make it even better.

Regards,
Sameel.
